actors=["keifer","kalix","jay-jay","mica","luna","yuri"]
print("Basic list functions")
print("---------------------------------------------------------------")
actors.append("ella")
print("Appending an element to the list using append() : \n",actors)
print("---------------------------------------------------------------")
actors.extend(["ci-n","keigen","keiren"])
print("adding more than one element to the list using extend() : \n",actors)
print("---------------------------------------------------------------")
actors.insert(0,"mark keifer watson")
print("Adding element at the sepcified index",actors)
print("---------------------------------------------------------------")
actors.reverse()
print("Revrese the list ",actors)
print("---------------------------------------------------------------")
actors.sort()
print("sort the list in ascending order",actors)
print("---------------------------------------------------------------")
actors.remove("jay-jay")
print("removes the firt occurance value from the list otherwise value error",actors)
print("---------------------------------------------------------------")
print("count the occurance of the provided string in the list ",actors.count("keifers"))
print("---------------------------------------------------------------")
print("returns the length of the list",len(actors))
print("---------------------------------------------------------------")
fakeactors=actors.copy()
print("Retuns a copy of list",fakeactors)
print("---------------------------------------------------------------")
print("removes and returns the specified indexed element from the list",actors.pop(2))
print("---------------------------------------------------------------")
print("prints the index value f the enterd element",actors.index("yuri"))
print("---------------------------------------------------------------")
fakeactors.clear()
print("clears the entire list : ",fakeactors)
print("---------------------------------------------------------------")
