st = "    hello team, i am 2mark Keifer Watson"
print("some basic functions in string")
print("--------------------------------")
print("returns the string in upper case : \n",st.upper())
print("--------------------------------")
print("returns the string in lower case : \n",st.lower())
print("--------------------------------")
print("returns the length of the string : \n",len(st))
print("--------------------------------")
print("returns the string by swaping their cases : \n",st.swapcase())
print("--------------------------------")
print("returns the string into a list of elements by dividing based on the delimeter provided as an argument ",st.split("m"))
print("--------------------------------")
print("returns a string by joining each character of the string with the provided delimeter","#".join(st))
print("--------------------------------")
print("returns count of the provided character/string as an argument : \n", st.count("k"))
print("--------------------------------")
print("retuns a string by replacing the characters passed in the arguments : \n",st.replace('Kei','val'))
print("--------------------------------")
print("caitalize the first chatacter of the string : \n",st.capitalize())
print("--------------------------------")
print("Capitalize the first chatacter of every word in the string : \n",st.title())
print("--------------------------------")
print("returns the index if the substring is found in the string otherwise retunns -1 : \n",st.find("Kei"))
print("--------------------------------")
print("retuns the string in lower case for caseinsensitive comparision: \n",st.casefold())
print("--------------------------------")
print("Centers the string with padding by deafult spaces but we can specify our own character : \n",st.center(40,"&"))
print("--------------------------------")
print("returns boolean value if the string starts with specifies substring : \n",st.startswith("hello"))
print("--------------------------------")
print("returns boolean value if the string ends with specifies substring : \n",st.endswith("watson"))
print("--------------------------------")
print("returns the index of the string if found oterwise returns value error : \n",st.index("h"))
print("--------------------------------")
print("returns a string byremoving leading and trailing spaces in the string : \n",st.strip())
print("--------------------------------")
print("returns boolean if all the characters in the string is in lower case : \n","Weather".islower())
print("--------------------------------")
print("returs boolean if all the characters in the string are in lowecase : \n","WEATEr".isupper())
print("--------------------------------")
print("returs boolean if all the characters in the string are in lowecase : \n","12345".isdigit())
print("--------------------------------")
print("returns boolean if all the characters in the string are numbers,fractions,subscrits or superscripts : \n","12".isnumeric())
print("--------------------------------")
print("12".isdecimal())
print("--------------------------------")
print(st.isalnum())
print("--------------------------------")
print(st.isspace())
print("--------------------------------")
print(st.istitle())
print("--------------------------------")
